overrides:
  content-security-policy-parser@<0.6.0: '>=0.6.0'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  esbuild@<=0.24.2: '>=0.25.0'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  msgpackr@<1.10.1: '>=1.10.1'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  svelte@<4.2.19: '>=4.2.19'
  svelte@<=5.51.4: '>=5.51.5'
  svelte@<=5.53.4: '>=5.53.5'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
