name: "✨ Feature Request"
description: Suggest a new feature or enhancement to an exiting feature
title: "[Feature]: "
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Provide a clear description of your idea
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution idea
      description: Provide a possible solution or approach to implement your idea
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Anything else that could be used to implement your idea, for example related issues.
